### ISSUE TITLE
Lists are not formatted correctly

### ISSUE THREAD

**Issue by rabernat** [m2lines/m2lines.github.io#17]
E.g. https://m2lines.github.io/jobs/

Our css stylesheet is setting  `list-style: none;`, which effectively suppresses formatting of lists. That's why all the lists on the jobs page just look like paragraphs.

I don't know enough about Hugo to debug this myself.

**Comment by johannag126** [comment]
can you point to the stylesheet you are referring to?

**Comment by johannag126** [comment]
I believe I have found a solution It works locally on my computer. I will upload it this week

**Comment by rabernat** [comment]
Sorry for not replying before. I don't know where the actual stylesheet lives. I was just using Chrome's "Inspect Elements" tool to inspect the styling.

**Comment by johannag126** [comment]
Fixed and uploaded
